version: '3.4'

services:
  api:
    image: eovconsulting/easysubapi
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: easysubapi
    environment:
      - TZ=Europe/Amsterdam
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=easysubapi_sqlserver2022;Database=EasySubDB;User Id=sa;Password=A&VeryComplex123Password;MultipleActiveResultSets=true;TrustServerCertificate=True
      - BotToken=7840281998:AAG7E9aGBXryBsVzWJg6tudm_8-yL5uL5uYVgw
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__Port=587
      - EmailSettings__Username=sva.records.o@gmail.com
      - EmailSettings__Password=tgal dqwm kydj csql
      - Stripe__WebhookSecret=whsec_llw4PwFuEoCSxSRsE5jFguLk4tEgEpxV
      - Stripe__SecretKey=sk_test_51RKNsaQMSCWUg7Iy5jDu8Pl2HHUIDKxFkTrB99enRKOyxftu5tJc7zT6sNrHndGKqqEs9jG3Tu2pHcjLFP3hTXpo005K1SKCpp
      - Stripe__PublishableKey=pk_test_51RKNsaQMSCWUg7Iy36ZcINrGCDJqYwfLEgI43KEinzsmkjsyPPMe95NeKyfhackWctNK17odBTUPM6TYjrfgl3rV00BzpL1THn
    ports:
      - "3000:80"
    depends_on:
      - sql
    restart: always

  web:
    image: eovconsulting/easysubaweb
    build:
      context: ./WWWeasySub
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiBaseUrl=http://144.91.114.243:3000/
    ports:
      - 3001:80
      
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: easysubapi_sqlserver2022
    user: root
    environment:
      - ACCEPT_EULA=y
      - TZ=Europe/Amsterdam
      - SA_PASSWORD=A&VeryComplex123Password
    ports:
      - "3002:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    restart: always